### ISSUE TITLE
admin/partners#edit: Current uploaded photo not appearing

### ISSUE THREAD

**Issue by mtornatta** [osu-cascades/hdffa-directory#69]
If you upload a partner photo from the partner edit page, then update, then return to the partner edit page. The spot where you upload a file says "no file chosen". We should have some way to display that a photo is already uploaded on the partner edit page.

**Comment by ybakos** [comment]
@mtornatta @Marji712 @KristenOrue Is this still open? If it is fixed, close the issue.

**Comment by KristenOrue** [comment]
Issue has been fixed, Photos/logos for Partners are now displayed in the show page after being uploaded.
