### ISSUE TITLE
develop: admin/partners_test#test_destroying_a_Partner failing

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/hdffa-directory#74]
@mtornatta @Marji712 @KristenOrue Always be sure that the tests are passing on the develop branch. There are commits here that refer to notes, but there is no migration.

Also, rename this test to use proper convention (capitalization is wrong)

**Comment by Marji712** [comment]
@ybakos tests are all passing currently(one skipped test, but not this one). Can you clarify what the test capitalization issue is; 
 should the titles be completely lowercase including class names?

**Comment by ybakos** [comment]
@Marji712 Ah, I misread some error output. You can disregard my statement about the naming.

**Comment by KristenOrue** [comment]
Great! Then since we have also created a migration for notes, this issue is resolved.
