### ISSUE TITLE
Note: Missing migration?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/hdffa-directory#75]
There is a Note model but there is no migration. Where is it?
@mtornatta @Marji712 @KristenOrue 

A Partner has a 1:M relationship to a Note. Not a M:N.

A User has a 1:M relationship to a Note. Not a M:N.

Therefor, a Note `belongs_to` a user and `belongs_to` a partner. And the migration should have:

- a `body`
- a partner_id and user_id

**Comment by ybakos** [comment]
When generating the migration, you can `rail g migration CreateNotes body:text partner:references user:references`

**Comment by Marji712** [comment]
@KristenOrue and I remade the model and generated the migration. Will need to run new migrations.
