### ISSUE TITLE
admin/partners#view:List all notes for partner on partner page

### ISSUE THREAD

**Issue by Marji712** [osu-cascades/hdffa-directory#77]
Show past notes in a scrollable area to the right of partner's other data. Newest note entries should be listed first.

**Comment by Marji712** [comment]
@KristenOrue we have the notes listed, but the are showing oldest at the top instead of newest

**Comment by KristenOrue** [comment]
Notes now display in descending order. I added a default scope to the note model so it now grabs the created_at attribute in descending order.
