### ISSUE TITLE
UI: Add notes history to front page

### ISSUE THREAD

**Issue by mtornatta** [osu-cascades/hdffa-directory#84]

**Comment by mtornatta** [comment]
Notes history card is now created but only displays a single note id so far.

**Comment by KristenOrue** [comment]
"http://localhost:3000/admin/notes/"
I created a 'admin/notes#index' View that displays all the same table attributes you need to display on the front page
if you go your browser and input: "http://localhost:3000/rails/info/routes" you can see which route leads to this view and maybe put that page within the front page somehow? Or maybe just copy similar code from that index page to the div you have set up for the notes history. Not sure, but this may be helpful
